#!/usr/bin/env ruby

require 'thor'

class Dotfiles < Thor
  desc "dotfiles", "Install all the dotfiles!"
  method_option :non_interactive, type: :boolean, default: false, aliases: "-n", desc: "Run non-interactively, existing files will be skipped by default"
  method_option :replace_all, type: :boolean, default: false, aliases: "-r", desc: "Replace all existing files"
  def dotfiles
    files = DIR['*'] - %w[Brewfile README.md LICENSE install.sh Thorfile]
    replace_all = options[:replace_all]
    non_interactive = options[:non_interactive]
    
    files.each do |file|
      dest_file = File.join(ENV['HOME'], ".#{file}")
      # system %Q{mkdir -p "$HOME/.#{File.dirname(file)}"} if file =~ /\//
      if File.exists?(dest_file)
        if File.identical? file, dest_file
          puts "identical ~/.#{file}"
        elsif replace_all
          replace_file(file)
        elsif non_interactive
          puts "skipping ~/.#{file}"
        else
          print "overwrite ~/.#{file}? [ynaq] "
          case stdin.gets.chomp
          when 'a'
            replace_all = true
            replace_file(file)
          when 'y'
            replace_file(file)
          when 'q'
            exit 0
          else
            puts "skipping ~/.#{file}"
          end
        end
      else
        link_file(file)
      end
    end
  end
  
  desc "software", "Install the apropriate software"
  def software
    
  end
  
  private
  
  def replace_file(file)
    system %Q{rm -rf "$HOME/.#{file}"}
    link_file(file)
  end
  
  def link_file(file)
    puts "linking #{file}"
    File.symlink(file, File.join(ENV['HOME'], ".#{file}"))
  end
end

Dotfiles.start(ARGV)